[{if $linenr == 0 }]
[{$encl}]Artikelnummer[{$encl}][{$spr}]
[{$encl}]Artikelname[{$encl}][{$spr}]
[{$encl}]EAN[{$encl}][{$spr}]
[{$encl}]Herstellername[{$encl}][{$spr}]
[{$encl}]Hersteller EAN[{$encl}][{$spr}]
[{$encl}]Beschreibung[{$encl}][{$spr}]
[{$encl}]PreisBruttoEuro[{$encl}][{$spr}]
[{$encl}]PreisNettoEuro[{$encl}][{$spr}]
[{$encl}]Bild[{$encl}][{$spr}]
[{$encl}]URL[{$encl}][{$spr}]
[{$encl}]Kategorie[{$encl}]
<br>
[{/if}]

[{$encl}][{$article->oxarticles__oxartnum->value}][{$encl}][{$spr}]
[{$encl}][{$article->oxarticles__oxtitle->value}][{$encl}][{$spr}]
[{$encl}][{$article->oxarticles__oxean->value}][{$encl}][{$spr}]
[{$encl}][{$sManufacturer}][{$encl}][{$spr}]
[{$encl}][{$article->oxarticles__oxdistean->value}][{$encl}][{$spr}]
[{$encl}][{$article->oxarticles__oxshortdesc->value}][{$encl}][{$spr}]
[{$encl}][{$sPriceBrut}][{$encl}][{$spr}]
[{$encl}][{$sPriceNet}][{$encl}][{$spr}]
[{$encl}][{$sPictureUrl}][{$encl}][{$spr}]
[{$encl}][{$article->getLink()|replace:"&amp;":"&"}][{$encl}][{$spr}]
[{$encl}][{$sCategory}][{$encl}]
